"""initial core and OAuth schema"""
from alembic import op
import sqlalchemy as sa
revision="0001_initial"; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
    op.create_table("products",sa.Column("id",sa.String(36),primary_key=True),sa.Column("sku",sa.String(80),unique=True),sa.Column("name",sa.String(240),nullable=False),sa.Column("product_type",sa.String(120)),sa.Column("collection",sa.String(120)),sa.Column("description",sa.Text()),sa.Column("facts",sa.JSON(),nullable=False),sa.Column("channel_content",sa.JSON(),nullable=False),sa.Column("ai_request_id",sa.String(120)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("media_assets",sa.Column("id",sa.String(36),primary_key=True),sa.Column("product_id",sa.String(36),sa.ForeignKey("products.id",ondelete="CASCADE"),nullable=False),sa.Column("original_filename",sa.String(255),nullable=False),sa.Column("stored_filename",sa.String(255),nullable=False,unique=True),sa.Column("mime_type",sa.String(120),nullable=False),sa.Column("media_type",sa.String(20),nullable=False),sa.Column("file_size",sa.Integer(),nullable=False),sa.Column("checksum",sa.String(64),nullable=False),sa.Column("role",sa.String(30)),sa.Column("alt_text",sa.Text()),sa.Column("sort_order",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_media_assets_product_id","media_assets",["product_id"]);op.create_index("ix_media_assets_checksum","media_assets",["checksum"])
    op.create_table("publications",sa.Column("id",sa.String(36),primary_key=True),sa.Column("product_id",sa.String(36),sa.ForeignKey("products.id",ondelete="CASCADE"),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("scheduled_at",sa.DateTime(timezone=True)),sa.Column("selected_media_ids",sa.JSON(),nullable=False),sa.Column("channel_content",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_publications_product_id","publications",["product_id"]);op.create_index("ix_publications_status","publications",["status"]);op.create_index("ix_publications_scheduled_at","publications",["scheduled_at"])
    op.create_table("deliveries",sa.Column("id",sa.String(36),primary_key=True),sa.Column("publication_id",sa.String(36),sa.ForeignKey("publications.id",ondelete="CASCADE"),nullable=False),sa.Column("channel",sa.String(40),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("attempt_count",sa.Integer(),nullable=False),sa.Column("next_attempt_at",sa.DateTime(timezone=True)),sa.Column("last_error",sa.Text()),sa.Column("external_post_id",sa.String(255)),sa.Column("external_url",sa.Text()),sa.Column("idempotency_key",sa.String(96),nullable=False,unique=True),sa.Column("published_at",sa.DateTime(timezone=True)))
    for col in ["publication_id","channel","status","next_attempt_at","idempotency_key"]: op.create_index(f"ix_deliveries_{col}","deliveries",[col])
    op.create_table("integration_accounts",sa.Column("id",sa.String(36),primary_key=True),sa.Column("provider",sa.String(40),nullable=False),sa.Column("account_key",sa.String(120),nullable=False),sa.Column("display_name",sa.String(240)),sa.Column("status",sa.String(30),nullable=False),sa.Column("scopes",sa.JSON(),nullable=False),sa.Column("encrypted_credentials",sa.Text()),sa.Column("expires_at",sa.DateTime(timezone=True)),sa.Column("last_checked_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("provider","account_key"));op.create_index("ix_integration_accounts_provider","integration_accounts",["provider"])
    op.create_table("oauth_states",sa.Column("id",sa.String(36),primary_key=True),sa.Column("provider",sa.String(40),nullable=False),sa.Column("state_hash",sa.String(64),nullable=False,unique=True),sa.Column("code_verifier_encrypted",sa.Text()),sa.Column("redirect_uri",sa.Text(),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("used_at",sa.DateTime(timezone=True)));op.create_index("ix_oauth_states_provider","oauth_states",["provider"]);op.create_index("ix_oauth_states_state_hash","oauth_states",["state_hash"]);op.create_index("ix_oauth_states_expires_at","oauth_states",["expires_at"])
    op.create_table("webhook_events",sa.Column("id",sa.String(36),primary_key=True),sa.Column("provider",sa.String(40),nullable=False),sa.Column("external_event_id",sa.String(160),nullable=False),sa.Column("payload",sa.JSON(),nullable=False),sa.Column("received_at",sa.DateTime(timezone=True),nullable=False),sa.Column("processed_at",sa.DateTime(timezone=True)),sa.Column("result",sa.Text()),sa.UniqueConstraint("provider","external_event_id"));op.create_index("ix_webhook_events_provider","webhook_events",["provider"])

def downgrade():
    for table in ["webhook_events","oauth_states","integration_accounts","deliveries","publications","media_assets","products"]: op.drop_table(table)
